// GENERATED FILE - DO NOT EDIT BY HAND.
// 由 tools/gen_field_help.py 从
// 参考资料/友商产品#2/standalone/catalog-schema.json 生成。
//
// 同款游戏第三方工坊编辑器的 schema，其 description 为字段的权威说明；
// 只收录非空项，其余交给 field_meta.dart 的规则/类型兜底。
library;

/// 配置表中文名：引用类字段的说明用它在文案里点名目标表。
const kFieldCfgLabels = <String, String>{
  'EvtCfg': '事件',
  'PersonCfg': 'NPC人物',
  'InteractCfg': 'NPC社交进度条文本',
  'TraitsCfg': 'NPC特质',
  'EndingPartCfg': 'NPC结局段落',
  'EndingOptionCfg': 'NPC结局选项',
  'BgCfg': '背景图',
  'CGCfg': 'CG图',
  'RenshengguanMemoryCfg': '珍贵记忆',
  'ItemCfg': '物品',
  'BookCfg': '书籍',
  'ActionCfg': '行动',
  'IntentCfg': '目标',
  'ShopCfg': '商店',
  'ActionEvtCfg': '行动随机触发事件',
  'AudioCfg': '背景音乐',
  'KZoneContentCfg': '企鹅空间动态',
  'KZoneCommentCfg': '企鹅空间评论',
  'KZoneAvatarCfg': '企鹅空间头像',
  'KZoneProfileCfg': '企鹅空间个人档',
  'ToggleCfg': '开关',
  'PhoneMsgCfg': '短信',
  'PersonAttrCfg': '属性',
  'PersonStateCfg': '状态/性格',
  'TalkCfg': '对话',
  'OptionCfg': '对话选项',
  'ModFaceCfg': '自定义表情',
  'PersonGrowCfg': '人物成长与喜好',
  'ItemTagCfg': '物品分类',
  'ConditionTypeCfg': '条件指令',
  'EffectTypeCfg': '效果指令',
  'EffectConstCfg': '效果组合',
  'SeasonTypeCfg': 'SeasonTypeCfg',
  'SkillCfg': '技能',
  'RelationCfg': '人物关系',
  'OtherRelationCfg': '关系组（条件判断用）',
  'MapCfg': '地图',
  'KZoneMessageBoardCfg': '企鹅留言',
  'FuncCfg': '功能',
  'EvtTypeCfg': 'EvtTypeCfg',
  'RenshengguanTypeCfg': 'RenshengguanTypeCfg',
  'ItemTypeCfg': 'ItemTypeCfg',
  'KZoneColorCfg': 'KZoneColorCfg',
  'KZoneFontCfg': 'KZoneFontCfg',
  'GiftEvtCfg': '送礼对话',
  'MovieCfg': '电影',
  'EndingDatingCfg': '相亲',
  'TextCfg': '全局文本',
  'JobCfg': '职业',
  'NegotiationPlayerCfg': '辩论对手',
  'FriendRequestCfg': '帮助同学',
  'ExploreCfg': '探索',
  'NegotiationSkillCfg': '交涉技能',
  'NegotiationBuffCfg': '交涉状态',
  'NewsCfg': '新闻',
  'NewsCommentCfg': '新闻评论',
  'NewsTypeCfg': '新闻分类',
  'AnimationCfg': '番剧',
  'AnimationTypeCfg': '番剧类型',
  'AnimationCostCfg': '搜番消耗',
  'AnimationRankCfg': '追番等级',
  'AnimationWifeCfg': '本命角色',
  'AnimeConCfg': '漫展活动',
  'AnimeConExpCfg': '漫展等级',
  'AnimeKzoneContentCfg': '追番动态',
  'AnimeMarkCntCfg': '追番标记',
  'TalkAnimeCfg': '聊番话题',
  'FishCfg': '鱼类',
  'FishTypeCfg': '鱼类等级',
  'FishBaitCfg': '鱼饵',
  'FishDiffCfg': '钓鱼手感',
  'TripSpotCfg': '旅游景点',
  'TripTypeCfg': '景点类型',
  'TripLevelCfg': '旅游等级',
  'TripEffectCfg': '旅游奖励',
  'ExpoSiteCfg': '世博展馆',
  'ExpoAttrCfg': '世博积分',
  'ExpoEvtCfg': '世博事件',
  'ClubActivityCfg': '社团活动',
  'ClubMemberCfg': '社团成员',
  'ClubDepartmentCfg': '社团部门',
  'ClubDailyCfg': '社团日常',
  'ClueRumorCfg': '线索与传闻',
  'ClubMemeberCntCfg': '社团人数',
  'ClubFundsCfg': '社团经费',
  'DIYCfg': '手工作品',
  'DIYRankCfg': '手工评级',
  'HandicraftMiniGameCfg': '手工拼装',
  'BirthdayPaintCfg': '生日猜画',
  'BirthdayPaintGuessCfg': '猜画人物反应',
  'BirthdayRewardCfg': '生日奖励',
  'BirthdayLvCfg': '派对等级',
  'BirthdayScoreCfg': '派对加分',
  'LineMatchMinigameCfg': '生日连线',
  'NegotiationTeamCfg': '交涉队伍',
  'NegotiationTeammateCfg': '可招募队友',
  'NegotiationTopicCfg': '辩论话题',
  'NegotiationMiniGameCardCfg': '普通牌组',
  'NegotiationMiniGameCardTypeCfg': '牌型与克制',
  'NegotiationUniqueCardCfg': '特殊卡牌',
  'NegotiationMiniGameCfg': '对局规则',
  'NegotiationInvolvedCfg': '交涉投入',
  'NegotiationCfg': '交涉行动',
  'NegotiationChatCfg': '交涉闲聊',
  'NegotiationTalkCfg': '交涉用语',
  'MomPowerCfg': '妈妈的牌组',
  'JobUnlockCfg': '职业解锁',
  'MinigameCfg': '小游戏总配置',
  'TVCfg': '电视节目',
  'LovePhotoboothCfg': '大头贴相框',
  'MinigameActionCfg': '社交关卡参数',
};

/// 字段级帮助文本（cfg → key → 说明），优先于跨表键描述与类型兜底。
const kFieldDescriptions = <String, Map<String, String>>{
  'EvtCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'talkId': '该事件首句对话的ID\n10位数字组成，左边7位为事件ID\n建议设置为1XXXXXX001',
    'displayType': '填以下数字\n0：默认，对话框的形式\n1：弹窗形式',
  },
  'InteractCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'text': '建议格式：\n正在和某人一起干某事\n\n参考：\n正在和谭梓君一起逛商场\n正在和肖清雅一起寻宝\n正在跟罗晓纯一本正经地开玩笑',
    'map': '指定地点出现此文本，不填表示任意地点\n可填多个，用逗号分隔\n\n填写以下ID\n1: 家\n2: 学校教学楼\n3: 学校操场\n4: 欣欣小卖部\n5: 百乐门游戏厅\n6: 新华书店\n7: 好宜多商场\n8: 星河电影院\n9: 鹅城博物馆\n10: 黄金海滩\n11: 长隆游乐园\n12: 鹅城客运站\n17: 双子峰\n101: 新开发区\n102: 南城名苑\n103: 老城区\n7002: 2楼服装区\n7003: 3楼娱乐区\n7004: 4楼达万影城\n17002: 祈福树\n17003: 山脚',
    'talkId': '进度条结束后出现的对话',
    'cond': '若不为空，需满足条件才可出现\n若为空，总是可出现',
  },
  'TraitsCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
  },
  'EndingPartCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'texture': '建议分辨率：1920x1080或2560x1440',
    'cond': '条件为空或者满足时显示此段落，\n不满足则寻找相同阶段的其他段落',
    'step': '填写以下数字\n0：沿用上一段落的阶段\n2：大学阶段&职业选择\n3：婚姻阶段\n5：35岁之后的职业故事或婚姻故事',
    'effect': '通常填写以下效果\n52,6,1=成为单身\n100,10,9002=打开婚礼开关，触发婚礼成就',
    'options': '填写NPC结局选项ID，用逗号分隔',
    'evt': '填写事件ID',
  },
  'EndingOptionCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'part': '填写跳转的NPC结局段落ID',
  },
  'BgCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'url': '建议分辨率：1920x1080或2560x1440',
  },
  'CGCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'urls': '建议分辨率：1920x1080或2560x1440',
    'gender': '用于同学录筛选性别\n0：男女主通用CG\n1：男主限定CG\n2：女主限定CG',
  },
  'RenshengguanMemoryCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
  },
  'ItemCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'icon': '建议分辨率：150x150像素且背景透明的png',
    'itemTag': '影响送礼的好感获取，可拥有多个标签，用逗号分隔',
    'value': '价值越高，送礼获得的好感越高\n-1表示不可赠送',
    'sell': '跳蚤市场的售价\n-1表示不可出售',
    'talkId': '生效时触发的对话id',
  },
  'BookCfg': {
    'id': '书籍ID\n7位数字组成，左边第一位固定为3\n例如：3XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'name': '手动填写书名号',
    'type': '3001:故事\n3002:知识',
    'itemTag': '影响送礼的好感获取，可拥有多个标签，用逗号分隔',
    'value': '价值越高，送礼获得的好感越高\n-1表示不可赠送',
    'sell': '跳蚤市场的售价\n-1表示不可出售',
    'themes':
        '主题id，可填多个，用逗号分隔\n1:益智\n2:现实\n4:励志\n5:少儿\n6:科普\n7:幻想\n9:历史\n11:古典',
  },
  'ActionCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'cnt': '大于0：每回合X次\n不填：无限次\n小于0：每X回合一次',
    'evtId': '若填写，则必定触发此事件\n若想触发随机事件，请编辑【行动随机触发事件】',
    'cost': '格式：属性,数值\n可以填多个，用分号分隔\n\n例如：\n消耗10点精力：7,10',
    'type': '0：普通行动\n3：恋爱行动\n4：兼职行动',
    'evtType': '行动发生时，在指定事件类型中搜索所有满足条件的事件并随机选择一个发生，仅支持恋爱行动使用',
    'attrs': '填写与此行动效果相关的属性ID\n用于大地图的提示\n可填多个，用逗号分隔',
  },
  'IntentCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'reward': '见文档中的“效果”格式',
    'demand': '见文档中的“前提/判断”格式',
    'npc': '影响目标面板显示谁的头像',
    'finishType': '0：完成时领取奖励后移除\n1：完成时自动移除\n2：只能用效果移除',
    'round': '持续指定回合数，超过则失败\n若为0，表示持续存在',
  },
  'ShopCfg': {
    'id': '和物品ID或书籍ID一致',
    'group': '同组别的物品只有其中一个会出现在商店中',
    'next': '当此商品被购买后，指定商品立刻在商店出现',
    'time': '游戏年份从2001开始到2013年结束',
    'discountRound': '指定回合开始才有可能参与打折\n游戏共有61回合\n详情见说明文档',
    'type': '1消耗品\n2装备\n3书籍\n4设备',
    'precondition': '前提满足时出现',
    'probability': '每年出现概率（0.0~1.0）',
    'buyTalk': '购买物品后，老板的闲聊',
  },
  'ActionEvtCfg': {
    'id': '和行动ID一致',
    'evts': '在满足前提的事件中，随机选择一个事件触发\n已触发的事件不再触发\n可填写多个，用逗号间隔',
    'rate': '触发事件的概率',
  },
  'AudioCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'url': '仅支持mp3、wav格式',
    'group': '填以下数字，可填多个，用逗号分隔\n0：默认\n2：社交时BGM\n3：春季BGM\n4：夏季BGM\n5：秋季BGM\n6：冬季BGM\n8：空间BGM',
  },
  'KZoneContentCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'role': '动态所有者ID',
    'thumbs': '选择点赞人物，并设置多久之后出现。',
    'comments': '选择这条动态的评论，并设置多久之后出现。',
    'options': '可填多个，用逗号分隔\n评论在【空间动态评论】中配置',
    'cond': '条件满足时自动出现\n若不填，只能通过效果发出此动态（23,1,X）',
  },
  'KZoneCommentCfg': {
    'id': '9位数字组成，左边7位为动态ID',
    'roles': '①某人评论动态：填『人物ID』\n②某人回复某人评论：填『人物ID,评论ID',
    'parent': '若此评论是直接回复动态，则此动态为根部评论，请填0\n否则填写最上级评论的ID',
    'comments': '选择这条动态的评论，并设置多久之后出现。',
    'options': '可填多个，用逗号分隔\n玩家只能选择其中一个评论',
    'effect': '玩家发出此评论之后获得的效果',
    'condition': '留空或者满足条件时自动评论',
  },
  'KZoneAvatarCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'icon': '建议分辨率：250x250px',
  },
  'KZoneProfileCfg': {
    'id': '和自定义人物ID一致',
    'marriage': '单身时的文本，脱单后的文本\n例如：单身,恋爱中',
    'isVip': '如果是黄钻，填1',
  },
  'ToggleCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复\n\n配合以下前提和效果使用：\n【前提】开关X是否打开：100,10,X\n【前提】开关X是否关闭：100,-10,X\n【效果】打开开关X：100,10,X\n【效果】关闭开关X：100,-10,X\n\n可作为记录某些状态的功能使用',
    'cond': '若为空，需要通过效果开启（100,10,X）\n若不为空，满足条件时自动开启\n通过效果关闭后，若后续仍满足条件，依然会开启\n只能通过效果关闭（100,-10,X）',
  },
  'PhoneMsgCfg': {
    'id': 'ID由7位数字组成\n左边第一位固定为1，建议最后三位为序号\n例如：1XXX001\n建议设置一个随机的数字，避免和其他mod重复\n\n注意：首句短信需要以001结尾',
    'role': '若此句由主角发出，则填0\n若此句由NPC发出，则填对应人物ID\n\n注意：001结尾的短信只能填人物ID',
    'next': '若不填，此句为短信结束\n若填一个，下一句短信会正常出现\n若填多个，表现为选项，需选择后才出对应的短信',
    'option': '若表现为选项，此处不能为空',
    'cond': '此处仅对001结尾的短信生效，设置了前提后才能自动出现\n\n否则使用效果发出短信：\n23,200,X',
  },
  'PersonAttrCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'min': '若填-1，表示无下限',
    'desc': '一句话介绍',
    'tag': '填写以下数字：\n10：普通属性\n13：性格关联属性',
    'valueInUI': '数值的显示格式\nint：整数（向下取整）\n{0:0.#%}：百分比\n若不填则保留一位小数',
    'consume': '0：不能消耗\n1：能消耗\n2：能消耗，且在最终结算中显示生涯累计值',
    'order': '若分类为性格关联属性，需填写性格ID',
  },
  'PersonStateCfg': {
    'id': 'ID由7位数字组成，\n左边第一位固定为1\n例如：1XXXXXX\n建议设置一个随机的数字，避免和其他mod重复',
    'hide': '0：显示为状态\n1：隐藏\n2：显示为性格',
    'attrId': '若为性格，此处必填，性格的数值随属性值变化',
    'effect': '见文档中的“效果”格式',
    'duration': '状态出现后，多少回合后消失\n0表示永久存在',
    'icon': '仅用于性格',
  },
  'PersonGrowCfg': {
    'ItemPref': '每项选择物品分类与喜好程度；普通表示没有额外偏好。',
    'attr': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
    'className': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
    'examRank': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
    'focusAttrId': '选择人物的重点属性。',
    'grow': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
    'id': '与人物资料使用同一个编号，由添加成长设置时选择的人物决定。',
    'personalitys': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
    'studyRank': '保留游戏原有参数顺序；尚未确认的数组位置不会自动解释或重排。',
  },
  'EndingDatingCfg': {'fix': '保留原版 fix 字段；当前相亲候选页面不使用此标记。'},
  'TextCfg': {'text': '保留 {0}、{1} 等占位符和原有富文本标签，游戏会在显示时填入参数。'},
  'JobCfg': {
    'scoreRate': '高考总分超过 550 分的部分 × 此倍率。',
    'weight': '依次对应一星、二星、三星；用于职业排序和结局选择。',
    'result': '第一行为 0 分的一星保底结局，再按最低评分从小到大添加。',
  },
  'NegotiationPlayerCfg': {
    'randBuff': '开局从列表中随机选择一个状态。',
    'attribute': '保持原版参数顺序。',
  },
  'FriendRequestCfg': {'effect': '原版将此数值加到主角人缘；消耗使用上方效果配置。'},
  'AnimationCostCfg': {'costs': '按第几次搜索的编号编辑；心情和体力搜索分别消耗对应属性。'},
  'DIYCfg': {'cost': '累计制作进度达到此值后完成作品。'},
  'BirthdayPaintGuessCfg': {'rate': '原版答对概率为 100 − 题目难度 + 系数 × 题目难度。'},
  'LineMatchMinigameCfg': {
    'lefts': '左右列表的同序号分组互相匹配；组内可添加多个候选词。',
    'rights': '与左侧同序号分组对应，游戏会打乱展示顺序。',
  },
};
