// GENERATED FILE - DO NOT EDIT BY HAND.
// 由 tools/gen_field_rules.py 从
// 参考资料中的第三方工坊编辑器 schema 生成。
//
// 同款游戏第三方工坊编辑器 schema 的 `range.table`：字段值是目标配置表
// 记录的 ID。无代码模式据此把这类字段判为「只选不敲」的 reference。
library;

/// `cfg:key` → 目标配置表名（值是该表记录 ID）。
/// 手写的 kRuleByCfgField / kRuleByField 优先，本表只做兜底。
const kFieldRefTargets = <String, String>{
  'ActionCfg:map': 'MapCfg',
  'AnimationCfg:type': 'AnimationTypeCfg',
  'AnimeConCfg:evtId': 'EvtCfg',
  'AnimeKzoneContentCfg:comments': 'KZoneCommentCfg',
  'AnimeKzoneContentCfg:thumb': 'PersonCfg',
  'BirthdayPaintCfg:npc': 'PersonCfg',
  'BirthdayRewardCfg:item': 'ItemCfg',
  'ClubActivityCfg:department': 'ClubDepartmentCfg',
  'ClubDailyCfg:attr': 'PersonAttrCfg',
  'ClubDepartmentCfg:attr': 'PersonAttrCfg',
  'EndingDatingCfg:icon': 'KZoneAvatarCfg',
  'EndingDatingCfg:jump': 'EndingPartCfg',
  'EvtCfg:mapId': 'MapCfg',
  'EvtCfg:options': 'OptionCfg',
  'EvtCfg:talkId': 'TalkCfg',
  'EvtCfg:type': 'EvtTypeCfg',
  'ExploreCfg:roleId': 'PersonCfg',
  'ExpoAttrCfg:attrId': 'PersonAttrCfg',
  'ExpoEvtCfg:evtId': 'EvtCfg',
  'ExpoSiteCfg:evt': 'EvtCfg',
  'FishBaitCfg:fishType': 'FishTypeCfg',
  'FishCfg:item': 'ItemCfg',
  'FishCfg:type': 'FishTypeCfg',
  'FriendRequestCfg:npc': 'PersonCfg',
  'GiftEvtCfg:npc': 'PersonCfg',
  'GiftEvtCfg:talkId': 'TalkCfg',
  'ItemCfg:type': 'ItemTypeCfg',
  'JobUnlockCfg:job': 'JobCfg',
  'KZoneCommentCfg:options': 'KZoneCommentCfg',
  'KZoneCommentCfg:parent': 'KZoneCommentCfg',
  'KZoneCommentCfg:roles': 'PersonCfg',
  'KZoneContentCfg:options': 'KZoneCommentCfg',
  'KZoneContentCfg:role': 'PersonCfg',
  'KZoneProfileCfg:font': 'KZoneFontCfg',
  'KZoneProfileCfg:fontColor': 'KZoneFontCfg',
  'KZoneProfileCfg:icon': 'KZoneAvatarCfg',
  'KZoneProfileCfg:theme': 'KZoneColorCfg',
  'MinigameActionCfg:loseTalk': 'TalkCfg',
  'MinigameActionCfg:needRelation': 'RelationCfg',
  'MinigameActionCfg:startTalk': 'TalkCfg',
  'MinigameActionCfg:winTalk': 'TalkCfg',
  'MinigameCfg:bgm': 'AudioCfg',
  'MovieCfg:attrs': 'PersonAttrCfg',
  'NegotiationCfg:before': 'NegotiationCfg',
  'NegotiationCfg:talks': 'TalkCfg',
  'NegotiationCfg:talks2': 'TalkCfg',
  'NegotiationMiniGameCardTypeCfg:attr': 'PersonAttrCfg',
  'NegotiationMiniGameCardTypeCfg:beRestraint': 'NegotiationMiniGameCardTypeCfg',
  'NegotiationMiniGameCardTypeCfg:restraint': 'NegotiationMiniGameCardTypeCfg',
  'NegotiationPlayerCfg:buff': 'NegotiationBuffCfg',
  'NegotiationPlayerCfg:npcId': 'PersonCfg',
  'NegotiationPlayerCfg:randBuff': 'NegotiationBuffCfg',
  'NegotiationPlayerCfg:skill': 'NegotiationSkillCfg',
  'NegotiationTalkCfg:reacts': 'NegotiationTalkCfg',
  'NegotiationTeamCfg:npcIds': 'NegotiationPlayerCfg',
  'NegotiationTeammateCfg:roleId': 'PersonCfg',
  'NegotiationTeammateCfg:skills': 'NegotiationSkillCfg',
  'NegotiationTopicCfg:buff1': 'NegotiationBuffCfg',
  'NegotiationTopicCfg:buff2': 'NegotiationBuffCfg',
  'NewsCfg:comments': 'NewsCommentCfg',
  'NewsCfg:type': 'NewsTypeCfg',
  'OptionCfg:nextEvtId': 'EvtCfg',
  'OptionCfg:talkId': 'TalkCfg',
  'OptionCfg:talkId2': 'TalkCfg',
  'PersonGrowCfg:focusAttrId': 'PersonAttrCfg',
  'PersonGrowCfg:items': 'ItemCfg',
  'PersonGrowCfg:speciality': 'TraitsCfg',
  'PersonGrowCfg:state': 'PersonStateCfg',
  'PersonGrowCfg:trait': 'TraitsCfg',
  'RenshengguanMemoryCfg:type': 'RenshengguanTypeCfg',
  'ShopCfg:type': 'ItemTypeCfg',
  'TalkCfg:audio': 'AudioCfg',
  'TalkCfg:bg': 'BgCfg',
  'TalkCfg:highlights': 'PersonCfg',
  'TalkCfg:nextTalk': 'TalkCfg',
  'TalkCfg:nextTalk2': 'TalkCfg',
  'TalkCfg:option': 'OptionCfg',
  'TalkCfg:replace': 'TalkCfg',
  'TalkCfg:roleIds': 'PersonCfg',
  'TripSpotCfg:evtId': 'EvtCfg',
  'TripSpotCfg:type': 'TripTypeCfg',
};
