// 工坊主页功能目录 —— 移植自参考产品（友商产品#2）的 workshop-features.json。
//
// 主页按此目录渲染功能卡片：每张卡片覆盖一组配置表，用户看到的是「功能」而不是
// 原始 CfgName；卡片可收藏、可搜索，对应参考产品「工坊主页」的功能清单。
library;

/// 一条主页功能定义。
class WorkshopFeature {
  const WorkshopFeature({
    required this.id,
    required this.label,
    required this.description,
    required this.homeCategory,
    this.tables = const [],
    this.group = '',
    this.primaryTable,
    this.entryKind,
    this.createLabel,
    this.resourceOnly = false,
    this.defaultFavorite = false,
    this.favoriteOrder = 0,
  });

  final String id;
  final String label;
  final String description;
  /// builtin / extension
  final String homeCategory;
  final List<String> tables;
  final String group;
  final String? primaryTable;
  final String? entryKind;
  final String? createLabel;
  final bool resourceOnly;
  final bool defaultFavorite;
  final int favoriteOrder;
}

const kWorkshopFeatures = <WorkshopFeature>[
  WorkshopFeature(
    id: 'story',
    label: '剧情编辑',
    description: '编写对话、安排人物、设置分支并播放剧情',
    homeCategory: 'builtin',
    tables: ['EvtCfg', 'TalkCfg', 'OptionCfg'],
    group: '常用功能',
    primaryTable: 'EvtCfg',
    entryKind: 'story',
    createLabel: '新建剧情',
    defaultFavorite: true,
  ),
  WorkshopFeature(
    id: 'persons',
    label: '人物',
    description: '添加人物并预览立绘、头像和表情',
    homeCategory: 'builtin',
    tables: ['PersonCfg', 'PersonGrowCfg', 'ModFaceCfg'],
    group: '常用功能',
    primaryTable: 'PersonCfg',
    entryKind: 'table',
    createLabel: '添加人物',
    defaultFavorite: true,
    favoriteOrder: 1,
  ),
  WorkshopFeature(
    id: 'items',
    label: '物品',
    description: '管理物品与书籍，选择图片、标签和使用效果',
    homeCategory: 'builtin',
    tables: ['ItemCfg', 'BookCfg'],
    group: '常用功能',
    primaryTable: 'ItemCfg',
    entryKind: 'table',
    createLabel: '添加物品',
    defaultFavorite: true,
    favoriteOrder: 3,
  ),
  WorkshopFeature(
    id: 'posts',
    label: '企鹅动态',
    description: '编辑作者、文字、配图、点赞和评论',
    homeCategory: 'builtin',
    tables: ['KZoneContentCfg'],
    group: '常用功能',
    primaryTable: 'KZoneContentCfg',
    entryKind: 'table',
    createLabel: '添加动态',
    defaultFavorite: true,
    favoriteOrder: 2,
  ),
  WorkshopFeature(
    id: 'traits',
    label: '人物特质',
    description: '为人物配置特质名称与效果',
    homeCategory: 'builtin',
    tables: ['TraitsCfg'],
    group: '人物',
    primaryTable: 'TraitsCfg',
    entryKind: 'table',
    createLabel: '添加特质',
  ),
  WorkshopFeature(
    id: 'endings',
    label: '结局段落',
    description: '编辑结局文字、配图和出现条件',
    homeCategory: 'builtin',
    tables: ['EndingPartCfg'],
    group: '结局与记忆',
    primaryTable: 'EndingPartCfg',
    entryKind: 'table',
    createLabel: '添加结局段落',
  ),
  WorkshopFeature(
    id: 'ending-options',
    label: '结局选项',
    description: '设置结局选项、关联段落和触发效果',
    homeCategory: 'builtin',
    tables: ['EndingOptionCfg'],
    group: '结局与记忆',
    primaryTable: 'EndingOptionCfg',
    entryKind: 'table',
    createLabel: '添加结局选项',
  ),
  WorkshopFeature(
    id: 'backgrounds',
    label: '场景背景',
    description: '添加背景图并预览场景',
    homeCategory: 'builtin',
    tables: ['BgCfg'],
    group: '场景与声音',
    primaryTable: 'BgCfg',
    entryKind: 'table',
    createLabel: '添加背景',
    resourceOnly: true,
  ),
  WorkshopFeature(
    id: 'cgs',
    label: 'CG 插图',
    description: '添加剧情插图并预览图片',
    homeCategory: 'builtin',
    tables: ['CGCfg'],
    group: '场景与声音',
    primaryTable: 'CGCfg',
    entryKind: 'table',
    createLabel: '添加 CG',
    resourceOnly: true,
  ),
  WorkshopFeature(
    id: 'memories',
    label: '珍贵记忆',
    description: '编辑记忆文字、配图及获得条件',
    homeCategory: 'builtin',
    tables: ['RenshengguanMemoryCfg'],
    group: '结局与记忆',
    primaryTable: 'RenshengguanMemoryCfg',
    entryKind: 'table',
    createLabel: '添加记忆',
  ),
  WorkshopFeature(
    id: 'actions',
    label: '行动',
    description: '设置行动名称、效果和触发事件',
    homeCategory: 'builtin',
    tables: ['ActionCfg'],
    group: '行动与目标',
    primaryTable: 'ActionCfg',
    entryKind: 'table',
    createLabel: '添加行动',
  ),
  WorkshopFeature(
    id: 'goals',
    label: '目标',
    description: '设置目标说明、达成要求和奖励',
    homeCategory: 'builtin',
    tables: ['IntentCfg'],
    group: '行动与目标',
    primaryTable: 'IntentCfg',
    entryKind: 'table',
    createLabel: '添加目标',
    defaultFavorite: true,
    favoriteOrder: 4,
  ),
  WorkshopFeature(
    id: 'shops',
    label: '商店商品',
    description: '设置商品、价格与出现时间',
    homeCategory: 'builtin',
    tables: ['ShopCfg'],
    group: '物品与商店',
    primaryTable: 'ShopCfg',
    entryKind: 'table',
    createLabel: '添加商品',
    defaultFavorite: true,
    favoriteOrder: 5,
  ),
  WorkshopFeature(
    id: 'audio',
    label: '音乐与音效',
    description: '添加声音素材并试听',
    homeCategory: 'builtin',
    tables: ['AudioCfg'],
    group: '场景与声音',
    primaryTable: 'AudioCfg',
    entryKind: 'table',
    createLabel: '添加声音',
    resourceOnly: true,
  ),
  WorkshopFeature(
    id: 'comments',
    label: '企鹅评论',
    description: '编辑评论、回复及玩家回复选项',
    homeCategory: 'builtin',
    tables: ['KZoneCommentCfg'],
    group: '企鹅空间',
    primaryTable: 'KZoneCommentCfg',
    entryKind: 'table',
    createLabel: '添加评论',
  ),
  WorkshopFeature(
    id: 'avatars',
    label: '企鹅头像',
    description: '添加头像并预览人物头像',
    homeCategory: 'builtin',
    tables: ['KZoneAvatarCfg'],
    group: '企鹅空间',
    primaryTable: 'KZoneAvatarCfg',
    entryKind: 'table',
    createLabel: '添加头像',
    resourceOnly: true,
  ),
  WorkshopFeature(
    id: 'profiles',
    label: '人物企鹅空间',
    description: '为自定义角色设置头像、空间音乐、签名、黄钻、个性名片与留言板',
    homeCategory: 'builtin',
    tables: ['KZoneProfileCfg'],
    group: '企鹅空间',
    primaryTable: 'KZoneProfileCfg',
    entryKind: 'table',
    createLabel: '添加企鹅空间',
  ),
  WorkshopFeature(
    id: 'switches',
    label: '条件开关',
    description: '设置供其他功能使用的条件开关',
    homeCategory: 'builtin',
    tables: ['ToggleCfg'],
    group: '逻辑设置',
    primaryTable: 'ToggleCfg',
    entryKind: 'table',
    createLabel: '添加开关',
  ),
  WorkshopFeature(
    id: 'idle-chats',
    label: '闲聊',
    description: '编辑人物闲聊、进度文字、地点、条件与效果',
    homeCategory: 'builtin',
    tables: ['InteractCfg', 'TalkCfg'],
    group: '剧情与互动',
    primaryTable: 'InteractCfg',
    entryKind: 'idle-chats',
    createLabel: '添加闲聊',
  ),
  WorkshopFeature(
    id: 'external-dialogues',
    label: '事件外对话',
    description: '保留和编辑小游戏、闲聊等不属于事件的对话',
    homeCategory: 'builtin',
    tables: ['TalkCfg'],
    group: '剧情与互动',
    primaryTable: 'TalkCfg',
    entryKind: 'external-dialogues',
    createLabel: '添加对话',
  ),
  WorkshopFeature(
    id: 'messages',
    label: '短信',
    description: '编辑人物短信、回复选项与后续消息',
    homeCategory: 'builtin',
    tables: ['PhoneMsgCfg'],
    group: '剧情与互动',
    primaryTable: 'PhoneMsgCfg',
    entryKind: 'table',
    createLabel: '添加短信',
  ),
  WorkshopFeature(
    id: 'attributes',
    label: '人物属性',
    description: '设置属性名称、数值说明和显示方式',
    homeCategory: 'builtin',
    tables: ['PersonAttrCfg'],
    group: '人物',
    primaryTable: 'PersonAttrCfg',
    entryKind: 'table',
    createLabel: '添加属性',
  ),
  WorkshopFeature(
    id: 'states',
    label: '状态与性格',
    description: '设置状态说明、持续回合和属性效果',
    homeCategory: 'builtin',
    tables: ['PersonStateCfg'],
    group: '人物',
    primaryTable: 'PersonStateCfg',
    entryKind: 'table',
    createLabel: '添加状态',
  ),
  WorkshopFeature(
    id: 'manifest',
    label: '模组信息',
    description: '编辑模组名称、介绍和封面',
    homeCategory: 'extension',
    group: '模组工具',
    entryKind: 'manifest',
    createLabel: '打开',
  ),
  WorkshopFeature(
    id: 'resources',
    label: '游戏素材',
    description: '读取本机图片、人物与声音素材',
    homeCategory: 'extension',
    group: '模组工具',
    entryKind: 'resources',
    createLabel: '打开',
  ),
  WorkshopFeature(
    id: 'movies',
    label: '电影',
    description: '配置票价、上映年份、观影效果和观后感',
    homeCategory: 'extension',
    tables: ['MovieCfg'],
    group: '玩法与配置',
    primaryTable: 'MovieCfg',
    entryKind: 'table',
    createLabel: '添加电影',
  ),
  WorkshopFeature(
    id: 'dating',
    label: '相亲',
    description: '编辑相亲资料、择偶门槛和结局去向',
    homeCategory: 'extension',
    tables: ['EndingDatingCfg'],
    group: '玩法与配置',
    primaryTable: 'EndingDatingCfg',
    entryKind: 'table',
    createLabel: '添加相亲',
  ),
  WorkshopFeature(
    id: 'global-text',
    label: '全局文本',
    description: '编辑游戏提示与说明，保留格式占位符',
    homeCategory: 'extension',
    tables: ['TextCfg'],
    group: '玩法与配置',
    primaryTable: 'TextCfg',
    entryKind: 'table',
    createLabel: '添加全局文本',
  ),
  WorkshopFeature(
    id: 'jobs',
    label: '职业',
    description: '配置职业评分、星级门槛和结局',
    homeCategory: 'extension',
    tables: ['JobCfg', 'JobUnlockCfg'],
    group: '玩法与配置',
    primaryTable: 'JobCfg',
    entryKind: 'table',
    createLabel: '添加职业',
  ),
  WorkshopFeature(
    id: 'negotiation-players',
    label: '辩论对手',
    description: '配置人物、能力、技能与开局状态',
    homeCategory: 'extension',
    tables: ['NegotiationPlayerCfg'],
    group: '玩法与配置',
    primaryTable: 'NegotiationPlayerCfg',
    entryKind: 'table',
    createLabel: '添加辩论对手',
  ),
  WorkshopFeature(
    id: 'friend-requests',
    label: '帮助同学',
    description: '编写求助、设置帮助条件和回应',
    homeCategory: 'extension',
    tables: ['FriendRequestCfg'],
    group: '玩法与配置',
    primaryTable: 'FriendRequestCfg',
    entryKind: 'table',
    createLabel: '添加帮助同学',
  ),
  WorkshopFeature(
    id: 'explorations',
    label: '探索',
    description: '配置探索目标、解锁要求和获得效果',
    homeCategory: 'extension',
    tables: ['ExploreCfg'],
    group: '玩法与配置',
    primaryTable: 'ExploreCfg',
    entryKind: 'table',
    createLabel: '添加探索',
  ),
  WorkshopFeature(
    id: 'flea-market',
    label: '跳蚤市场',
    description: '配置市场解锁、入口行动与物品书籍售价',
    homeCategory: 'extension',
    tables: ['ExploreCfg', 'ActionCfg', 'ItemCfg', 'BookCfg'],
    group: '玩法与配置',
    primaryTable: 'ExploreCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'news',
    label: '新闻与评论',
    description: '编排新闻、配图、刊登条件与读者评论',
    homeCategory: 'extension',
    tables: ['NewsCfg', 'NewsCommentCfg', 'NewsTypeCfg'],
    group: '玩法与配置',
    primaryTable: 'NewsCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'anime',
    label: '看番与漫展',
    description: '管理番剧、本命、漫展活动及追番成长',
    homeCategory: 'extension',
    tables: ['AnimationCfg', 'AnimeConCfg', 'AnimationTypeCfg', 'AnimationWifeCfg', 'AnimationRankCfg', 'AnimationCostCfg', 'AnimeConExpCfg', 'AnimeKzoneContentCfg', 'AnimeMarkCntCfg', 'TalkAnimeCfg'],
    group: '玩法与配置',
    primaryTable: 'AnimationCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'fishing',
    label: '钓鱼',
    description: '配置鱼类、鱼饵、图鉴奖励和钓鱼手感',
    homeCategory: 'extension',
    tables: ['FishCfg', 'FishBaitCfg', 'FishTypeCfg', 'FishDiffCfg'],
    group: '玩法与配置',
    primaryTable: 'FishCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'travel',
    label: '旅游',
    description: '编辑景点、游览效果与旅游成长',
    homeCategory: 'extension',
    tables: ['TripSpotCfg', 'TripTypeCfg', 'TripLevelCfg', 'TripEffectCfg'],
    group: '玩法与配置',
    primaryTable: 'TripSpotCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'expo',
    label: '世博会',
    description: '编排展馆、游览事件与积分奖励',
    homeCategory: 'extension',
    tables: ['ExpoSiteCfg', 'ExpoAttrCfg', 'ExpoEvtCfg'],
    group: '玩法与配置',
    primaryTable: 'ExpoSiteCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'detective-club',
    label: '侦探社',
    description: '配置部门、成员、活动、调查与经费',
    homeCategory: 'extension',
    tables: ['ClubActivityCfg', 'ClubMemberCfg', 'ClubDepartmentCfg', 'ClubDailyCfg', 'ClueRumorCfg', 'ClubMemeberCntCfg', 'ClubFundsCfg'],
    group: '玩法与配置',
    primaryTable: 'ClubActivityCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'crafts',
    label: '手工',
    description: '设置作品、制作前提、评级与拼装判定点',
    homeCategory: 'extension',
    tables: ['DIYCfg', 'DIYRankCfg', 'HandicraftMiniGameCfg'],
    group: '玩法与配置',
    primaryTable: 'DIYCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'birthday-party',
    label: '生日派对',
    description: '编辑猜画与连线题目、人物反应和派对奖励',
    homeCategory: 'extension',
    tables: ['BirthdayPaintCfg', 'LineMatchMinigameCfg', 'BirthdayPaintGuessCfg', 'BirthdayRewardCfg', 'BirthdayLvCfg', 'BirthdayScoreCfg'],
    group: '玩法与配置',
    primaryTable: 'BirthdayPaintCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'negotiation-teams',
    label: '交涉队伍',
    description: '组建参赛队伍、配置对手和可招募队友',
    homeCategory: 'extension',
    tables: ['NegotiationTeamCfg', 'NegotiationTeammateCfg', 'NegotiationPlayerCfg'],
    group: '玩法与配置',
    primaryTable: 'NegotiationTeamCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'negotiation-topics',
    label: '交涉话题',
    description: '设置正反方观点、状态、交涉行动和回应',
    homeCategory: 'extension',
    tables: ['NegotiationTopicCfg', 'NegotiationCfg', 'NegotiationTalkCfg', 'NegotiationChatCfg', 'NegotiationInvolvedCfg'],
    group: '玩法与配置',
    primaryTable: 'NegotiationTopicCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'negotiation-decks',
    label: '交涉牌组',
    description: '配置普通牌、特殊牌、克制、技能与对局规则',
    homeCategory: 'extension',
    tables: ['NegotiationMiniGameCardCfg', 'NegotiationUniqueCardCfg', 'NegotiationMiniGameCardTypeCfg', 'NegotiationSkillCfg', 'NegotiationBuffCfg', 'NegotiationMiniGameCfg', 'MomPowerCfg'],
    group: '玩法与配置',
    primaryTable: 'NegotiationMiniGameCardCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'job-unlocks',
    label: '职业解锁',
    description: '设置职业开放条件与解锁提示',
    homeCategory: 'extension',
    tables: ['JobUnlockCfg', 'JobCfg'],
    group: '玩法与配置',
    primaryTable: 'JobUnlockCfg',
    entryKind: 'table',
    createLabel: '添加内容',
  ),
  WorkshopFeature(
    id: 'minigames',
    label: '小游戏',
    description: '修改原版小游戏和社交关卡的参数、消耗与对话',
    homeCategory: 'builtin',
    tables: ['MinigameCfg', 'MinigameActionCfg', 'HandicraftMiniGameCfg', 'LineMatchMinigameCfg', 'NegotiationMiniGameCfg', 'NegotiationMiniGameCardCfg', 'NegotiationMiniGameCardTypeCfg'],
    group: '玩法与配置',
    primaryTable: 'MinigameCfg',
    entryKind: 'table',
  ),
  WorkshopFeature(
    id: 'television',
    label: '电视节目',
    description: '编辑频道、节目、本集标题、观看条件和效果',
    homeCategory: 'builtin',
    tables: ['TVCfg'],
    group: '玩法与配置',
    primaryTable: 'TVCfg',
    entryKind: 'table',
    createLabel: '添加电视节目',
  ),
  WorkshopFeature(
    id: 'love-confession',
    label: '表白与成功率',
    description: '调整概率提示、颜色和人物成功率参数。',
    homeCategory: 'extension',
    tables: ['LoveVindicateCfg', 'LoveVindicateRateCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveVindicateCfg',
    entryKind: 'table',
    createLabel: '添加表白',
  ),
  WorkshopFeature(
    id: 'love-actions',
    label: '约会行动',
    description: '编辑约会行动名称与功能编号',
    homeCategory: 'extension',
    tables: ['LoveActionCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveActionCfg',
    entryKind: 'table',
    createLabel: '添加约会行动',
  ),
  WorkshopFeature(
    id: 'love-badminton',
    label: '羽毛球',
    description: '编辑羽毛球各环节台词',
    homeCategory: 'extension',
    tables: ['LoveBadmintonCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveBadmintonCfg',
    entryKind: 'table',
    createLabel: '添加羽毛球台词',
  ),
  WorkshopFeature(
    id: 'love-breakfast',
    label: '爱心早餐',
    description: '编辑人物赠送早餐的物品、消息与条件',
    homeCategory: 'extension',
    tables: ['LoveBreakfastCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveBreakfastCfg',
    entryKind: 'table',
    createLabel: '添加爱心早餐',
  ),
  WorkshopFeature(
    id: 'love-draw',
    label: '情侣画',
    description: '编辑原有画笔颜色、画作素材、获得条件与对话。',
    homeCategory: 'extension',
    tables: ['LoveDrawCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveDrawCfg',
    entryKind: 'table',
    createLabel: '添加情侣画',
  ),
  WorkshopFeature(
    id: 'love-wish',
    label: '祈福许愿',
    description: '编辑祈福飘带与许愿内容效果',
    homeCategory: 'extension',
    tables: ['LoveRibbonCfg', 'WishCfg'],
    group: '恋爱与送礼',
    primaryTable: 'LoveRibbonCfg',
    entryKind: 'table',
    createLabel: '添加祈福',
  ),
  WorkshopFeature(
    id: 'gift-events',
    label: '送礼事件',
    description: '编辑送礼物品、人物、条件与对话',
    homeCategory: 'extension',
    tables: ['GiftEvtCfg'],
    group: '恋爱与送礼',
    primaryTable: 'GiftEvtCfg',
    entryKind: 'table',
    createLabel: '添加送礼事件',
  ),
];
