// AUTO-GENERATED zip fixtures for [p3b] tests (docx/xlsx/resource packs).
// Python zipfile ZIP_DEFLATED+ZIP_STORED — exercises the miniz inflate path.
// Regenerate recipe documented in STATUS.md (M7).
#pragma once

#include <string>

// docx: 4 paragraphs, entities &#26816;=检, tab/br (506 bytes raw)
inline const std::string kDOCX =
    "UEsDBBQAAAAAAAAAIQDHHBc8CAAAAAgAAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbDxUeXBlcy8+UEsDBBQAAAAIAAAAIQCK"
    "enCj/AAAAKUBAAARAAAAd29yZC9kb2N1bWVudC54bWyFkLFOwzAQhl/lZKRu1GmGqEqTdGNiYCgP4MSmjRT7LNsQurGxsSAx"
    "IZhgirohZeFt0vAaxECFQJW6/Ke7/9N/0p/Mr2UFV8LYElVKJuOAgFAF8lItU3K+ODmeErCOKc4qVCIla2HJPEvqmGNxKYVy"
    "MAQoG9cpWTmnY0ptsRKS2TFqoQbvAo1kbljNktZouDZYCGuHfFnRMAgiKlmpiI/Mka/91F6MF5d9NE3X3vSbt/7htn9sEuqP"
    "Xs2X6v/8GTPsD7RzWE6/iUWN+4Dc/PinpRLhwT8AcJDZtq8wYlLPYLt56t7vu/YORkdhNJ1EM+ifX/YE0F0L9Lfh7BNQSwEC"
    "FAAUAAAAAAAAACEAxxwXPAgAAAAIAAAAEwAAAAAAAAAAAAAAgAEAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQIUABQAAAAI"
    "AAAAIQCKenCj/AAAAKUBAAARAAAAAAAAAAAAAACAATkAAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAgACAIAAAABkAQAA"
    "AAA=";


// xlsx: 2 sheets, sharedStrings(3), inlineStr, out-of-range idx (1524 bytes raw)
inline const std::string kXLSX =
    "UEsDBBQAAAAAAAAAIQAO6JQrFQEAABUBAAAPAAAAeGwvd29ya2Jvb2sueG1sPD94bWwgdmVyc2lvbj0iMS4wIj8+PHdvcmti"
    "b29rIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvc3ByZWFkc2hlZXRtbC8yMDA2L21haW4iIHht"
    "bG5zOnI9Imh0dHA6Ly9zY2hlbWFzLm9wZW54bWxmb3JtYXRzLm9yZy9vZmZpY2VEb2N1bWVudC8yMDA2L3JlbGF0aW9uc2hp"
    "cHMiPjxzaGVldHM+PHNoZWV0IG5hbWU9IuaIkOe7qeihqCIgcjppZD0icklkMSIvPjxzaGVldCBuYW1lPSLnrKzkuozkuKoi"
    "IHI6aWQ9InJJZDIiLz48L3NoZWV0cz48L3dvcmtib29rPlBLAwQUAAAACAAAACEAva346ZIAAAD/AAAAGgAAAHhsL19yZWxz"
    "L3dvcmtib29rLnhtbC5yZWxzbc9LCoNADADQqww5gFEXXRRH126LFxg0dcTPDElo7e07FAq1uMqXF1I1+7qYB7FMYbNQZDk0"
    "dXWjxWlqiJ+imLSxiQWvGq+I0ntanWQh0pYm98Cr01TyiNH1sxsJyzy/IP8acDRNO1jgdijAdK9IFjQljkdSC8/As3giFfyE"
    "IktXAM+B8gTAfcF/pPwieHitfgNQSwMEFAAAAAgAAAAhAIF0UaqOAAAAtQAAABQAAAB4bC9zaGFyZWRTdHJpbmdzLnhtbLOx"
    "r8jNUShLLSrOzM+zVTLUM1Cyt7MpLi5RAIrnFdsqZZSUFFjp6xcnZ6TmJhbr5Rek5gFl0vKLchNLgNyidP3igqLUxJTijNTU"
    "ktwcfSMDAzP93MTMPCWgMZl2NiV2T5dPfjqh10a/xM5GHyQCFd2z4MmOTlTRIrDE+h6IKJj3bFr7szlrEMr0gU6zAwBQSwME"
    "FAAAAAgAAAAhAFnis0XRAAAAfAEAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxtkE1uwjAQha8S+QCZ/EClVI5RCzfg"
    "BFZwG4vYjuxRwpYFnIArVuoxOgRkpSK7mffefPYM35xMlwzKB+1szfI0YxvBR+ePoVUKE3JtqFmL2L8DhKZVRobU9cqS8+W8"
    "kUit/4bQeyUP05DpoMiyNzBSWyb4pO0kSsG9GxNPr5Da3IuPnCVYs0D9IDIOg+DQPL1tPqnVOspA45FRREYxY+T/GZ8PT9tO"
    "W7VHTxkdBEfxc738nm8ckMJ35QVfRnw5w1fV8mdWU3phk0cKZieAeFvxB1BLAwQUAAAACAAAACEALJL/64IAAACsAAAAGAAA"
    "AHhsL3dvcmtzaGVldHMvc2hlZXQyLnhtbE1OWwrDMAy7SsgB6mwfGww3hdGLhMxbypoHTkh3/Ln9GPuwkCULGadPXFUnrktO"
    "oz4NRk8Wt8zvGoiaEjfVUYfWyg2g+kDR1SEXSuI8M0fXZOUX1MLkHkcornA25gLRLUlbPLTZNWeR86ZYWkT1O7nvrNsrQrcI"
    "XkYuBP8i8PvFfgFQSwECFAAUAAAAAAAAACEADuiUKxUBAAAVAQAADwAAAAAAAAAAAAAAgAEAAAAAeGwvd29ya2Jvb2sueG1s"
    "UEsBAhQAFAAAAAgAAAAhAL2t+OmSAAAA/wAAABoAAAAAAAAAAAAAAIABQgEAAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxz"
    "UEsBAhQAFAAAAAgAAAAhAIF0UaqOAAAAtQAAABQAAAAAAAAAAAAAAIABDAIAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAhQA"
    "FAAAAAgAAAAhAFnis0XRAAAAfAEAABgAAAAAAAAAAAAAAIABzAIAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQIUABQA"
    "AAAIAAAAIQAskv/rggAAAKwAAAAYAAAAAAAAAAAAAACAAdMDAAB4bC93b3Jrc2hlZXRzL3NoZWV0Mi54bWxQSwUGAAAAAAUA"
    "BQBTAQAAiwQAAAAA";


// resource pack: manifest(测试包/0.9) + aa_index + Cfgs/zh-cn/TestCfg (412 bytes raw)
inline const std::string kPACK =
    "UEsDBBQAAAAAAAAAIQBxwUW1JwAAACcAAAANAAAAbWFuaWZlc3QuanNvbnsibmFtZSI6ICLmtYvor5XljIUiLCAidmVyc2lv"
    "biI6ICIwLjkifVBLAwQUAAAACAAAACEAv4XttgkAAAAHAAAADQAAAGFhX2luZGV4Lmpzb26rVipTsjKuBQBQSwMEFAAAAAgA"
    "AAAhAKV/hFYQAAAAEAAAABcAAABDZmdzL3poLWNuL1Rlc3RDZmcuanNvbqtWMlSyUqhWykwBUoa1tQBQSwECFAAUAAAAAAAA"
    "ACEAccFFtScAAAAnAAAADQAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QuanNvblBLAQIUABQAAAAIAAAAIQC/he22CQAAAAcA"
    "AAANAAAAAAAAAAAAAACAAVIAAABhYV9pbmRleC5qc29uUEsBAhQAFAAAAAgAAAAhAKV/hFYQAAAAEAAAABcAAAAAAAAAAAAA"
    "AIABhgAAAENmZ3MvemgtY24vVGVzdENmZy5qc29uUEsFBgAAAAADAAMAuwAAAMsAAAAAAA==";


// pack without manifest.json (backfill path) (137 bytes raw)
inline const std::string kPACK_NO_MANIFEST =
    "UEsDBBQAAAAIAAAAIQBmj+R5EwAAABEAAAAKAAAAZGljdHMuanNvbqtWSk/MTY1PyUwuKVayqq6tBQBQSwECFAAUAAAACAAA"
    "ACEAZo/keRMAAAARAAAACgAAAAAAAAAAAAAAgAEAAAAAZGljdHMuanNvblBLBQYAAAAAAQABADgAAAA7AAAAAAA=";


// zip with .. member (install must reject) (216 bytes raw)
inline const std::string kPACK_BAD_ENTRY =
    "UEsDBBQAAAAAAAAAIQBDv6ajAgAAAAIAAAAHAAAAb2suanNvbnt9UEsDBBQAAAAAAAAAIQBDv6ajAgAAAAIAAAAMAAAALi4v"
    "ZXZpbC5qc29ue31QSwECFAAUAAAAAAAAACEAQ7+mowIAAAACAAAABwAAAAAAAAAAAAAAgAEAAAAAb2suanNvblBLAQIUABQA"
    "AAAAAAAAIQBDv6ajAgAAAAIAAAAMAAAAAAAAAAAAAACAAScAAAAuLi9ldmlsLmpzb25QSwUGAAAAAAIAAgBvAAAAUwAAAAAA";


// zip with /abs member (install must reject) (121 bytes raw)
inline const std::string kPACK_ABS_ENTRY =
    "UEsDBBQAAAAAAAAAIQCDFtyMAQAAAAEAAAALAAAAL2V0Yy9wYXNzd2R4UEsBAhQAFAAAAAAAAAAhAIMW3IwBAAAAAQAAAAsA"
    "AAAAAAAAAAAAAIABAAAAAC9ldGMvcGFzc3dkUEsFBgAAAAABAAEAOQAAACoAAAAAAA==";

