// AUTO-GENERATED by native/wip/P3b/gen_domain_table.py from
// backend/editor/server/ai_domain_service.py::AI_DOMAINS. Do not hand-edit.
#pragma once

#include <string>
#include <utility>
#include <vector>

namespace sa {
namespace p3b {

struct DomainTableEntry {
    const char* id;
    const char* name;
    const char* desc;
    // (cfg, 中文名) —— 源顺序；get_domains 输出前需自行按 cfg 排序
    std::vector<std::pair<std::string, std::string>> tables;
};

inline const std::vector<DomainTableEntry>& ai_domains() {
    static const std::vector<DomainTableEntry> kDomains = {
        {"story", "剧情", "事件、对话、选项、行动等剧情内容", {{"EvtCfg", "事件"}, {"TalkCfg", "对话"}, {"OptionCfg", "选项"}, {"EvtTypeCfg", "事件类型"}, {"TalkAnimeCfg", "对话立绘动画"}, {"ActionCfg", "行动"}, {"ActionEvtCfg", "行动事件"}, {"ActionTalkCfg", "行动对话"}, {"ActionTypeCfg", "行动类型"}, {"ClassTalkCfg", "课堂对话"}, {"BargainTalkCfg", "砍价对话"}}},
        {"character", "人物", "人物基础、成长、属性、性格、姓名、称号、外观等", {{"PersonCfg", "人物"}, {"PersonGrowCfg", "人物成长"}, {"PersonAttrCfg", "人物属性"}, {"PersonHobbyCfg", "人物爱好"}, {"PersonStateCfg", "人物状态"}, {"PersonFaceCfg", "人物表情"}, {"PersonConstCfg", "人物常量"}, {"PersonalityTypeCfg", "性格类型"}, {"PersonalityTestCfg", "性格测试"}, {"PersonalityInfluenceCfg", "性格影响"}, {"PersonalityLevelCfg", "性格等级"}, {"TraitsCfg", "特质"}, {"NameCfg", "名字"}, {"NicknameCfg", "昵称"}, {"MottoCfg", "座右铭"}, {"MottoLVCfg", "座右铭等级"}, {"RelationCfg", "关系"}, {"OtherRelationCfg", "其他关系"}, {"AcquaintancesNumberCfg", "熟人数量"}, {"InitialSettingCfg", "初始设置"}, {"SpecializationCfg", "专长"}, {"ModFaceCfg", "捏脸"}, {"ClothTypeCfg", "服装"}, {"HairTypeCfg", "发型"}}},
        {"background", "背景与场景", "背景图、地图、音乐音效、CG、画面特效", {{"BgCfg", "背景图"}, {"MapCfg", "地图"}, {"AudioCfg", "音乐音效"}, {"CGCfg", "CG"}, {"ShaderCfg", "画面特效"}, {"ColorCfg", "颜色"}, {"AnimeConCfg", "动画条件"}, {"AnimeConExpCfg", "动画条件经验"}, {"AnimeKzoneContentCfg", "动画空间动态"}, {"AnimeMarkCntCfg", "动画标记数"}}},
        {"social", "社交", "空间动态、短信、闲聊、新闻、好友", {{"KZoneContentCfg", "空间动态"}, {"KZoneCommentCfg", "空间评论"}, {"KZoneAvatarCfg", "空间头像"}, {"KZoneColorCfg", "空间颜色"}, {"KZoneFontCfg", "空间字体"}, {"KZoneMessageBoardCfg", "空间留言板"}, {"KZoneProfileCfg", "空间装扮"}, {"PhoneMsgCfg", "手机短信"}, {"InteractCfg", "闲聊"}, {"FriendRequestCfg", "好友申请"}, {"NewsCfg", "新闻"}, {"NewsCommentCfg", "新闻评论"}, {"NewsTypeCfg", "新闻类型"}, {"ThanksNameCfg", "感谢称呼"}, {"Review2Cfg", "回评"}}},
        {"love", "恋爱与结局", "送礼、恋爱约会、生日、结局、家庭", {{"GiftEvtCfg", "送礼事件"}, {"LoveActionCfg", "恋爱行动"}, {"LoveBadmintonCfg", "恋爱羽毛球"}, {"LoveBreakfastCfg", "爱心早餐"}, {"LoveDrawCfg", "恋爱绘画"}, {"LoveGreetingCfg", "恋爱问候"}, {"LovePhotoboothCfg", "恋爱拍照"}, {"LoveRibbonCfg", "恋爱缎带"}, {"LoveVindicateCfg", "恋爱辩解"}, {"LoveVindicateRateCfg", "恋爱辩解概率"}, {"BirthdayLvCfg", "生日等级"}, {"BirthdayPaintCfg", "生日涂鸦"}, {"BirthdayPaintGuessCfg", "生日涂鸦猜谜"}, {"BirthdayRewardCfg", "生日奖励"}, {"BirthdayScoreCfg", "生日分数"}, {"EndingDatingCfg", "结局约会"}, {"EndingOptionCfg", "结局选项"}, {"EndingPartCfg", "结局章节"}, {"MomPowerCfg", "妈妈力"}, {"NpcChunSupportCfg", "春支持"}, {"NpcJunChaosCfg", "君巢"}}},
        {"item", "物品与商店", "物品、商店、书籍、试卷、道具", {{"ItemCfg", "物品"}, {"ItemTagCfg", "物品标签"}, {"ItemTypeCfg", "物品类型"}, {"ShopCfg", "商店"}, {"HonorShopCfg", "荣誉商店"}, {"FightItemCfg", "战斗道具"}, {"BookCfg", "书籍"}, {"BookThemeCfg", "书籍主题"}, {"PaperCfg", "试卷"}, {"WishCfg", "许愿"}, {"DivinationCfg", "占卜"}, {"FishCfg", "鱼"}, {"FishBaitCfg", "鱼饵"}, {"FishDiffCfg", "钓鱼难度"}, {"FishTypeCfg", "鱼类型"}}},
        {"achievement", "成就与称号", "成就、称号、荣誉排行", {{"AchievementCfg", "成就"}, {"AchEffectCfg", "成就效果"}, {"AchIncreaseCfg", "成就提升"}, {"AchRankCfg", "成就排行"}, {"AchRefreshCfg", "成就刷新"}, {"GlobalAchCfg", "全局成就"}, {"SocialAchievementCfg", "社交成就"}, {"HonorRankCfg", "荣誉排行"}, {"RankCfg", "排行"}}},
        {"study", "学习与考试", "课程、作业、考试、学习方法、知识、成绩", {{"LessonCfg", "课程"}, {"HomeworkCfg", "作业"}, {"ExamBrickCfg", "考试砖块"}, {"ExamLevelCfg", "考试等级"}, {"ExamStepCfg", "考试步骤"}, {"FinalExamScoreCfg", "期末考试分数"}, {"StudyMethodCfg", "学习方法"}, {"StudyMethodIncresseCfg", "学习方法提升"}, {"StudyPressureCfg", "学习压力"}, {"StudyStrategyCfg", "学习策略"}, {"StudyStrategyCostCfg", "学习策略消耗"}, {"StudySummaryCfg", "学习总结"}, {"StudySummaryRewardCfg", "学习总结奖励"}, {"KnowledgeCfg", "知识"}, {"KnowledgeQuestionsCfg", "知识问答"}, {"KnowledgeTalkTextCfg", "知识对话文本"}, {"KnowledgeTreeCfg", "知识树"}, {"TestPaperCfg", "测试卷"}, {"ScoreCfg", "成绩"}, {"ScoreFormulaCfg", "成绩公式"}, {"ScoreParmCfg", "成绩参数"}, {"ScoreRankCfg", "成绩排行"}, {"GradeCfg", "年级"}, {"EducationCfg", "教育"}, {"UnivercityCfg", "大学"}, {"UnivercityRankCfg", "大学排行"}, {"ReadBookCostCfg", "读书消耗"}, {"MotiveCfg", "动机"}, {"IntrospectionCardCfg", "内省卡"}, {"IntrospectionFrequencyCfg", "内省频率"}, {"IntrospectionProgressCfg", "内省进度"}, {"IntrospectionSlotCfg", "内省槽"}}},
        {"club", "社团与活动", "社团、日常活动、季节、出游、展会", {{"ClubActivityCfg", "社团活动"}, {"ClubDailyCfg", "社团日常"}, {"ClubDepartmentCfg", "社团部门"}, {"ClubFundsCfg", "社团资金"}, {"ClubMemberCfg", "社团成员"}, {"ClubMemeberCntCfg", "社团人数"}, {"ActivityCfg", "活动"}, {"NpcActivityCfg", "NPC活动"}, {"SeasonCfg", "季节"}, {"SeasonTypeCfg", "季节类型"}, {"SiteWeightCfg", "地点权重"}, {"TripEffectCfg", "出游效果"}, {"TripLevelCfg", "出游等级"}, {"TripSpotCfg", "出游地点"}, {"TripTypeCfg", "出游类型"}, {"ExpoAttrCfg", "展会属性"}, {"ExpoEvtCfg", "展会事件"}, {"ExpoSiteCfg", "展会展位"}, {"GoBtnCfg", "按钮"}}},
        {"minigame", "小游戏", "各类小游戏的题目、关卡、配置", {{"MinigameCfg", "小游戏"}, {"MinigameActionCfg", "小游戏行动"}, {"BrickMinigameCfg", "砖块小游戏"}, {"CrosswordMinigameCfg", "填字小游戏"}, {"DrawingMinigameCfg", "绘画小游戏"}, {"HandicraftMiniGameCfg", "手工小游戏"}, {"HongbaoMiniGameCfg", "红包小游戏"}, {"LineMatchMinigameCfg", "连线小游戏"}, {"MusicMinigameCfg", "音乐小游戏"}, {"PianoCfg", "钢琴"}, {"PianoKeyCfg", "钢琴键"}, {"PuzzleMinigameCfg", "拼图小游戏"}, {"Qte3MinigameCfg", "QTE小游戏"}, {"SentenceMiniGameCfg", "造句小游戏"}, {"StudyCardMiniGameCfg", "学习卡小游戏"}, {"StudyCardRateMiniGameCfg", "学习卡概率"}, {"TalkInputMinigameCfg", "打字小游戏"}, {"WeavingMinigameCfg", "编织小游戏"}, {"VoteTurntableCfg", "投票转盘"}, {"QuizAICfg", "问答AI"}, {"QuizCardCfg", "问答卡"}, {"QuizCompetitionCfg", "问答竞赛"}, {"QuizPlayerReduceCfg", "问答减员"}, {"QuizTypeCfg", "问答类型"}}},
        {"battle", "运动与对战", "篮球、羽毛球、谈判、DND 等玩法数值", {{"Basketball1On1Cfg", "篮球单挑"}, {"BasketballPlayerCfg", "篮球球员"}, {"BasketballSkinCfg", "篮球皮肤"}, {"BadmintonLevelCfg", "羽毛球等级"}, {"BadmintonModelCfg", "羽毛球模型"}, {"NegotiationCfg", "谈判"}, {"NegotiationBuffCfg", "谈判增益"}, {"NegotiationChatCfg", "谈判对话"}, {"NegotiationInvolvedCfg", "谈判参与"}, {"NegotiationMiniGameCfg", "谈判小游戏"}, {"NegotiationMiniGameCardCfg", "谈判卡牌"}, {"NegotiationMiniGameCardTypeCfg", "谈判卡牌类型"}, {"NegotiationPlayerCfg", "谈判玩家"}, {"NegotiationSkillCfg", "谈判技能"}, {"NegotiationTalkCfg", "谈判对话文本"}, {"NegotiationTeamCfg", "谈判队伍"}, {"NegotiationTeammateCfg", "谈判队友"}, {"NegotiationTopicCfg", "谈判话题"}, {"NegotiationUniqueCardCfg", "谈判特殊卡"}, {"FightPlayerCfg", "战斗玩家"}, {"SportConstCfg", "运动常量"}}},
        {"job", "职业与兼职", "职业、兼职需求、NPC 教学", {{"JobCfg", "职业"}, {"JobUnlockCfg", "职业解锁"}, {"IntDemandCfg", "兼职需求"}, {"TeachNpcCfg", "NPC教学"}}},
        {"world", "世界观与文案", "世界观、描述、文本、编年史、影视、写作", {{"WorldviewCfg", "世界观"}, {"DescriptionCfg", "描述"}, {"TextCfg", "文本"}, {"LoadingTxtCfg", "加载文本"}, {"ChronologyCfg", "编年史"}, {"WikiCfg", "百科"}, {"TVCfg", "电视"}, {"MovieCfg", "电影"}, {"MuseumNameCfg", "博物馆名"}, {"WritingCfg", "写作"}, {"WritingEffectCfg", "写作效果"}, {"WritingRankCfg", "写作排行"}, {"RenshengguanMemoryCfg", "人生馆记忆"}, {"RenshengguanSkillCfg", "人生馆技能"}, {"RenshengguanTypeCfg", "人生馆类型"}, {"InfluenceCfg", "影响"}}},
        {"function", "功能与系统", "功能开关、引导、快捷键、红点、游戏全局参数", {{"FuncCfg", "功能"}, {"FuncTypeCfg", "功能类型"}, {"GuideCfg", "引导"}, {"GuideGroupCfg", "引导组"}, {"GuideImgCfg", "引导图"}, {"GuideNegotiationCfg", "引导谈判"}, {"GuideStateCfg", "引导状态"}, {"HotKeyCfg", "快捷键"}, {"InputActionCfg", "输入动作"}, {"ConsoleCodeCfg", "控制台代码"}, {"RedpointCfg", "红点"}, {"ToggleCfg", "开关"}, {"LocalizeAssetCfg", "本地化资源"}, {"GameCfg", "游戏参数"}, {"GameDiffCfg", "游戏难度"}, {"GamePlatformCfg", "游戏平台"}, {"GameTypeCfg", "游戏类型"}, {"EffectConstCfg", "效果常量"}, {"EffectTypeCfg", "效果类型"}, {"ConditionTypeCfg", "条件类型"}, {"OtherAttrCfg", "其他属性"}, {"ValueviewCfg", "数值视图"}, {"ValueviewEffectCfg", "数值视图效果"}, {"ValueviewGraphCfg", "数值视图图表"}, {"AttrUnitCfg", "属性单位"}, {"AttrUnitCondCfg", "属性单位条件"}}},
    };
    return kDomains;
}

}  // namespace p3b
}  // namespace sa
