# -*- coding: utf-8 -*-
"""P3b 一次性代码生成器：把 ai_domain_service.AI_DOMAINS 烘成 C++ 头。

用法（仓库根）：
    python native/wip/P3b/gen_domain_table.py
输出：native/wip/P3b/p3b_domain_table.h（勿手改）。
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "backend"))

from editor.server.ai_domain_service import AI_DOMAINS  # noqa: E402


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    lines = [
        "// AUTO-GENERATED by native/wip/P3b/gen_domain_table.py from",
        "// backend/editor/server/ai_domain_service.py::AI_DOMAINS. Do not hand-edit.",
        "#pragma once",
        "",
        "#include <string>",
        "#include <utility>",
        "#include <vector>",
        "",
        "namespace sa {",
        "namespace p3b {",
        "",
        "struct DomainTableEntry {",
        "    const char* id;",
        "    const char* name;",
        "    const char* desc;",
        "    // (cfg, 中文名) —— 源顺序；get_domains 输出前需自行按 cfg 排序",
        "    std::vector<std::pair<std::string, std::string>> tables;",
        "};",
        "",
        "inline const std::vector<DomainTableEntry>& ai_domains() {",
        "    static const std::vector<DomainTableEntry> kDomains = {",
    ]
    for d in AI_DOMAINS:
        pairs = ", ".join('{"%s", "%s"}' % (esc(k), esc(v)) for k, v in d["tables"].items())
        lines.append('        {"%s", "%s", "%s", {%s}},'
                     % (esc(d["id"]), esc(d["name"]), esc(d["desc"]), pairs))
    lines += [
        "    };",
        "    return kDomains;",
        "}",
        "",
        "}  // namespace p3b",
        "}  // namespace sa",
        "",
    ]
    out = os.path.join(HERE, "p3b_domain_table.h")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d domains, %d table entries)"
          % (out, len(AI_DOMAINS), sum(len(d["tables"]) for d in AI_DOMAINS)))


if __name__ == "__main__":
    main()
